// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYb2-CLRZYd6OKTbB0v9oKjS661rx42-M',
    appId: '1:1082955061928:web:0d0db5a489550dc6c0009d',
    messagingSenderId: '1082955061928',
    projectId: 'coach-studio-2026',
    authDomain: 'coach-studio-2026.firebaseapp.com',
    storageBucket: 'coach-studio-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR1O559oJcNa2M8SO0ui9xOORCil2MHCc',
    appId: '1:1082955061928:android:44249b2a40e2e1a6c0009d',
    messagingSenderId: '1082955061928',
    projectId: 'coach-studio-2026',
    storageBucket: 'coach-studio-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOBH7jBf_mlrRME7PeJ77Gkxxl_JWBejw',
    appId: '1:1082955061928:ios:d62f943d9b5fade0c0009d',
    messagingSenderId: '1082955061928',
    projectId: 'coach-studio-2026',
    storageBucket: 'coach-studio-2026.firebasestorage.app',
    iosBundleId: 'com.example.coachStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOBH7jBf_mlrRME7PeJ77Gkxxl_JWBejw',
    appId: '1:1082955061928:ios:d62f943d9b5fade0c0009d',
    messagingSenderId: '1082955061928',
    projectId: 'coach-studio-2026',
    storageBucket: 'coach-studio-2026.firebasestorage.app',
    iosBundleId: 'com.example.coachStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYb2-CLRZYd6OKTbB0v9oKjS661rx42-M',
    appId: '1:1082955061928:web:23c417ba5e6f32c0c0009d',
    messagingSenderId: '1082955061928',
    projectId: 'coach-studio-2026',
    authDomain: 'coach-studio-2026.firebaseapp.com',
    storageBucket: 'coach-studio-2026.firebasestorage.app',
  );
}
